# python run_cfkd.py --config "<PEAL_BASE>/configs/sce_experiments/adaptors/Smiling_confounding_CopyrightTag_celeba1000x100_ace_cfkd.yaml"
adaptor_type                         :  "CFKD"
category                             :  "adaptor"
batch_size                           :  4
tracking_level                       :  4
min_train_samples                    :  800
finetune_iterations                  :  1
max_validation_samples               :  200
continuous_learning                  :  "finetune"
calculate_explainer_stats            :  True
calculate_group_accuracies           :  True
explainer                            :  <PEAL_BASE>/configs/sce_experiments/explainers/ace_default.yaml
training                             :  <PEAL_BASE>/configs/sce_experiments/training/img_finetuning.yaml
data                                 :  <PEAL_BASE>/configs/sce_experiments/data/Smiling_confounding_copyrighttag_celeba_poisoned100.yaml
test_data                            :  <PEAL_BASE>/configs/sce_experiments/data/Smiling_confounding_copyrighttag_celeba.yaml
base_dir                             :  $PEAL_RUNS/celeba_copyrighttag/Smiling_confounding_copyrighttag/regularized0/classifier_poisoned100/ace_cfkd
student                              :  $PEAL_RUNS/celeba_copyrighttag/Smiling_confounding_copyrighttag/regularized0/classifier_poisoned100/model.cpl
teacher                              :  $PEAL_RUNS/celeba_copyrighttag/Smiling_confounding_copyrighttag/regularized0/classifier_unpoisoned/model.cpl
generator                            :  $PEAL_RUNS/celeba_copyrighttag/ddpm/config.yaml
task:
  criterions:
    ce     : 1.0
    l2     : 100.0
  output_type             : singleclass
  output_channels         : 2
  y_selection             : [Smiling]